/*
Datos estáticos generados con IAG, 
contiene datos artificiales de avistamientos 
y datos artificiales de voluntarios 
*/

const sightingData = [
    { id: 1,  birdType: "Passeriformes",     birdName: "Chercán",              region: "Región Metropolitana",     comuna: "Ñuñoa",                 date: "2025-08-20", time: "08:15", file: { type: "foto",  name: "chercan_nunoa.jpg" } },
    { id: 2,  birdType: "Passeriformes",     birdName: "Zorzal",               region: "Valparaíso",                comuna: "Viña del Mar",          date: "2025-08-15", time: "07:40", file: { type: "foto",  name: "zorzal_vina.jpg" } },
    { id: 3,  birdType: "Pelecaniformes",    birdName: "Bandurria",            region: "Región de Los Lagos",       comuna: "Puerto Montt",          date: "2025-08-10", time: "09:00", file: { type: "video", name: "bandurria_pto_montt.mp4" } },
    { id: 4,  birdType: "Passeriformes",     birdName: "Tordo",                region: "Región del Biobío",         comuna: "Concepción",            date: "2025-07-28", time: "18:20", file: { type: "foto",  name: "tordo_concepcion.jpg" } },
    { id: 5,  birdType: "Passeriformes",     birdName: "Diucón",               region: "Región de la Araucanía",    comuna: "Temuco",                date: "2023-07-22", time: "10:05", file: { type: "foto",  name: "diucon_temuco.jpg" } },
    { id: 6,  birdType: "Cathartiformes",    birdName: "Cóndor Andino",        region: "Región de Magallanes",      comuna: "Punta Arenas",          date: "2022-07-15", time: "12:30", file: { type: "video", name: "condor_pta_arenas.mp4" } },
    { id: 7,  birdType: "Passeriformes",     birdName: "Chincol",              region: "Región Metropolitana",     comuna: "Providencia",           date: "2025-07-05", time: "08:50", file: { type: "foto",  name: "chincol_providencia.jpg" } },
    { id: 8,  birdType: "Ciconiiformes",     birdName: "Garza Grande",         region: "Coquimbo",                  comuna: "La Serena",             date: "2021-06-28", time: "17:10", file: { type: "foto",  name: "garza_la_serena.jpg" } },
    { id: 9,  birdType: "Falconiformes",     birdName: "Tiuque",               region: "Valparaíso",                comuna: "Valparaíso",            date: "2025-06-18", time: "09:45", file: { type: "foto",  name: "tiuque_valpo.jpg" } },
    { id: 10, birdType: "Apodiformes",       birdName: "Picaflor Gigante",     region: "Arica y Parinacota",        comuna: "Arica",                 date: "2025-06-10", time: "11:00", file: { type: "foto",  name: "picaflor_arica.jpg" } },
    { id: 11, birdType: "Passeriformes",     birdName: "Loica",                region: "Región de Ñuble",           comuna: "Chillán",               date: "2020-05-30", time: "08:00", file: { type: "video", name: "loica_chillan.mp4" } },
    { id: 12, birdType: "Suliformes",        birdName: "Yeco",                 region: "Región de Los Ríos",        comuna: "Valdivia",              date: "2025-05-20", time: "07:30", file: { type: "foto",  name: "yeco_valdivia.jpg" } },
    { id: 13, birdType: "Passeriformes",     birdName: "Zorzal",               region: "Región Metropolitana",     comuna: "Maipú",                 date: "2025-05-12", time: "19:00", file: { type: "foto",  name: "zorzal_maipu.jpg" } },
    { id: 14, birdType: "Passeriformes",     birdName: "Chercán",              region: "Región del Biobío",         comuna: "Talcahuano",            date: "2025-04-25", time: "08:40", file: { type: "foto",  name: "chercan_talcahuano.jpg" } },
    { id: 15, birdType: "Pelecaniformes",    birdName: "Bandurria",            region: "Región de O'Higgins",       comuna: "Rancagua",              date: "2025-04-10", time: "09:20", file: { type: "foto",  name: "bandurria_rancagua.jpg" } },
    { id: 16, birdType: "Passeriformes",     birdName: "Diucón",               region: "Valparaíso",                comuna: "Quilpué",               date: "2025-03-30", time: "10:15", file: { type: "video", name: "diucon_quilpue.mp4" } },
    { id: 17, birdType: "Piciformes",        birdName: "Carpintero Negro",     region: "Región de Los Ríos",        comuna: "Panguipulli",           date: "2025-02-14", time: "09:10", file: { type: "foto",  name: "carpintero_panguipulli.jpg" } },
    { id: 18, birdType: "Psittaciformes",    birdName: "Tricahue",             region: "Región de O'Higgins",       comuna: "San Fernando",          date: "2025-02-20", time: "16:45", file: { type: "foto",  name: "tricahue_sanfernando.jpg" } },
    { id: 19, birdType: "Columbiformes",     birdName: "Tórtola",              region: "Región Metropolitana",     comuna: "Las Condes",            date: "2025-01-18", time: "08:30", file: { type: "foto",  name: "tortola_lascondes.jpg" } },
    { id: 20, birdType: "Charadriiformes",   birdName: "Gaviota Dominicana",   region: "Atacama",                   comuna: "Caldera",               date: "2025-01-25", time: "07:50", file: { type: "foto",  name: "gaviota_caldera.jpg" } },
    { id: 21, birdType: "Galliformes",       birdName: "Codorniz",             region: "Región de la Araucanía",    comuna: "Villarrica",            date: "2024-12-10", time: "08:00", file: { type: "foto",  name: "codorniz_villarrica.jpg" } },
    { id: 22, birdType: "Anseriformes",      birdName: "Pato Real",            region: "Región de Los Lagos",       comuna: "Castro",                date: "2024-12-05", time: "07:15", file: { type: "video", name: "pato_real_castro.mp4" } },
    { id: 23, birdType: "Strigiformes",      birdName: "Lechuza Blanca",       region: "Región del Biobío",         comuna: "Los Ángeles",           date: "2024-11-20", time: "20:30", file: { type: "foto",  name: "lechuza_losangeles.jpg" } },
    { id: 24, birdType: "Sphenisciformes",   birdName: "Pingüino de Humboldt", region: "Antofagasta",               comuna: "Antofagasta",           date: "2024-11-08", time: "10:00", file: { type: "foto",  name: "pinguino_antofagasta.jpg" } },
    { id: 25, birdType: "Phoenicopteriformes", birdName: "Flamenco Chileno",   region: "Antofagasta",               comuna: "San Pedro de Atacama",  date: "2024-10-22", time: "15:20", file: { type: "foto",  name: "flamenco_sanpedro.jpg" } },
    { id: 26, birdType: "Rheiformes",        birdName: "Ñandú",                region: "Región de Magallanes",      comuna: "Natales",               date: "2024-10-15", time: "09:40", file: { type: "video", name: "nandu_natales.mp4" } },
    { id: 27, birdType: "Gruiformes",        birdName: "Tagua",                region: "Región de Ñuble",           comuna: "San Carlos",            date: "2024-09-28", time: "08:10", file: { type: "foto",  name: "tagua_sancarlos.jpg" } },
    { id: 28, birdType: "Procellariiformes", birdName: "Petrel",               region: "Tarapacá",                  comuna: "Iquique",               date: "2024-09-14", time: "07:00", file: { type: "foto",  name: "petrel_iquique.jpg" } },
    { id: 29, birdType: "Cuculiformes",      birdName: "Crespín",              region: "Región del Maule",          comuna: "Talca",                 date: "2024-09-02", time: "18:00", file: { type: "foto",  name: "crespin_talca.jpg" } },
    { id: 30, birdType: "Tinamiformes",      birdName: "Perdiz Chilena",       region: "Región de Aisén",           comuna: "Coihaique",             date: "2024-08-25", time: "08:45", file: { type: "foto",  name: "perdiz_coihaique.jpg" } },
    { id: 31, birdType: "Coraciiformes",     birdName: "Martín Pescador",      region: "Región de Los Ríos",        comuna: "Valdivia",              date: "2024-08-18", time: "09:30", file: { type: "foto",  name: "martin_pescador_valdivia.jpg" } },
    { id: 32, birdType: "Podicipediformes",  birdName: "Blanquillo",           region: "Coquimbo",                  comuna: "Ovalle",                date: "2024-08-05", time: "07:45", file: { type: "video", name: "blanquillo_ovalle.mp4" } },
];

// Voluntarios registrados
const volunteerData = [
    { id: 1,  region: "Región Metropolitana",  registrationDate: "2025-01-10" },
    { id: 2,  region: "Región Metropolitana",  registrationDate: "2025-02-14" },
    { id: 3,  region: "Valparaíso",            registrationDate: "2025-01-22" },
    { id: 4,  region: "Región del Biobío",     registrationDate: "2025-03-05" },
    { id: 5,  region: "Región de Los Lagos",   registrationDate: "2025-02-18" },
    { id: 6,  region: "Región de la Araucanía",registrationDate: "2025-04-02" },
    { id: 7,  region: "Región Metropolitana",  registrationDate: "2023-05-11" },
    { id: 8,  region: "Coquimbo",              registrationDate: "2025-03-20" },
    { id: 9,  region: "Valparaíso",            registrationDate: "2022-04-15" },
    { id: 10, region: "Región de Magallanes",  registrationDate: "2025-05-30" },
    { id: 11, region: "Región Metropolitana",  registrationDate: "2025-06-08" },
    { id: 12, region: "Región del Biobío",     registrationDate: "2021-06-22" },
    { id: 13, region: "Atacama",               registrationDate: "2025-02-02" },
    { id: 14, region: "Tarapacá",              registrationDate: "2025-03-15" },
    { id: 15, region: "Antofagasta",           registrationDate: "2025-02-25" },
    { id: 16, region: "Región de la Araucanía",registrationDate: "2025-03-10" },
    { id: 17, region: "Región de Aisén",       registrationDate: "2025-03-18" },
    { id: 18, region: "Región del Maule",      registrationDate: "2025-04-22" },
    { id: 19, region: "Región de Ñuble",       registrationDate: "2025-05-02" },
    { id: 20, region: "Región de Los Ríos",    registrationDate: "2025-05-15" },
    { id: 21, region: "Región de O'Higgins",   registrationDate: "2025-06-01" },
    { id: 22, region: "Arica y Parinacota",    registrationDate: "2025-06-15" },
    { id: 23, region: "Región de Magallanes",  registrationDate: "2025-07-01" },
    { id: 24, region: "Región Metropolitana",  registrationDate: "2025-07-20" },
];