const regionesComunas = {
    "Arica y Parinacota": ["Arica", "Camarones", "Putre", "General Lagos"],
    "Tarapacá": ["Iquique", "Alto Hospicio", "Pica", "Huara", "Pozo Almonte", "Colchane", "Camiña"],
    "Antofagasta": ["Antofagasta", "Calama", "Tocopilla", "Mejillones", "Sierra Gorda", "Taltal", "San Pedro de Atacama", "Ollagüe"],
    "Atacama": ["Copiapó", "Vallenar", "Caldera", "Tierra Amarilla", "Chañaral", "Diego de Almagro", "Huasco", "Freirina", "Alto del Carmen"],
    "Coquimbo": ["La Serena", "Coquimbo", "Vicuña", "Ovalle", "Illapel", "Salamanca", "Los Vilos", "Andacollo", "Paihuano", "Monte Patria", "Combarbalá", "Punitaqui", "Río Hurtado", "Canela"],
    "Valparaíso": ["Valparaíso", "Viña del Mar", "Concón", "Quilpué", "Villa Alemana", "San Antonio", "San Felipe", "Los Andes", "Quillota", "Limache", "Olmué", "Calera", "Cartagena", "Casablanca", "El Quisco", "El Tabo", "Isla de Pascua", "Juan Fernández", "La Ligua", "Llay Llay", "Nogales", "Puchuncaví", "Quintero", "Rinconada", "San Esteban", "Santa María", "Santo Domingo", "Zapallar"],
    "Metropolitana": ["Santiago", "Providencia", "Las Condes", "Vitacura", "Ñuñoa", "La Reina", "Peñalolén", "Macul", "La Florida", "San Miguel", "San Joaquín", "La Cisterna", "El Bosque", "Pedro Aguirre Cerda", "Lo Espejo", "San Ramón", "La Granja", "Renca", "Quinta Normal", "Cerro Navia", "Lo Prado", "Pudahuel", "Maipú", "Estación Central", "Cerrillos", "Conchalí", "Huechuraba", "Independencia", "Recoleta", "Colina", "Lampa", "Til Til", "Pirque", "Puente Alto", "San José de Maipo", "Buin", "Calera de Tango", "Paine", "Talagante", "El Monte", "Isla de Maipo", "Melipilla", "Curacaví", "María Pinto", "San Pedro", "Alhué"],
    "O'Higgins": ["Rancagua", "Machalí", "Graneros", "Codegua", "Mostazal", "Coinco", "Coltauco", "Doñihue", "Pichidegua", "Quinta de Tilcoco", "Rengo", "Requínoa", "San Vicente", "Pichilemu", "La Estrella", "Litueche", "Marchihue", "Navidad", "Paredones", "Chépica", "Chimbarongo", "Lolol", "Nancagua", "Palmilla", "Peralillo", "Placilla", "Pumanque", "Santa Cruz"],
    "Maule": ["Talca", "Curicó", "Linares", "Constitución", "Cauquenes", "San Javier", "Molina", "Pencahue", "Río Claro", "San Clemente", "Sagrada Familia", "Pelarco", "Maule", "Empedrado", "Villa Alegre", "Yerbas Buenas", "Retiro", "Parral", "Longaví", "Colbún", "San Rafael", "Hualañé", "Licantén", "Rauco", "Romeral", "Teno", "Vichuquén"],
    "Ñuble": ["Chillán", "Chillán Viejo", "Bulnes", "Cobquecura", "Coelemu", "Coihueco", "El Carmen", "Ninhue", "Ñiquén", "Pemuco", "Pinto", "Portezuelo", "Quirihue", "Ránquil", "San Carlos", "San Fabián", "San Ignacio", "San Nicolás", "Treguaco", "Yungay"],
    "Biobío": ["Concepción", "Talcahuano", "Hualpén", "Chiguayante", "Coronel", "Lota", "Penco", "Tomé", "Florida", "Hualqui", "Santa Juana", "San Pedro de la Paz", "Los Ángeles", "Cabrero", "Quilaco", "Quilleco", "San Rosendo", "Santa Bárbara", "Tucapel", "Yumbel", "Mulchén", "Negrete", "Nacimiento", "Laja", "Alto Biobío", "Antuco"],
    "Araucanía": ["Temuco", "Padre Las Casas", "Angol", "Collipulli", "Curacautín", "Ercilla", "Lonquimay", "Los Sauces", "Lumaco", "Purén", "Renaico", "Traiguén", "Victoria", "Villarrica", "Gorbea", "Loncoche", "Pitrufquén", "Pucón", "Saavedra", "Teodoro Schmidt", "Freire", "Carahue", "Cholchol", "Cunco", "Curarrehue", "Galvarino", "Melipeuco", "Nueva Imperial", "Perquenco", "Toltén"],
    "Los Ríos": ["Valdivia", "Corral", "Lanco", "Los Lagos", "Máfil", "Mariquina", "Paillaco", "Panguipulli", "La Unión", "Futrono", "Lago Ranco", "Río Bueno"],
    "Los Lagos": ["Puerto Montt", "Calbuco", "Cochamó", "Fresia", "Frutillar", "Llanquihue", "Los Muermos", "Maullín", "Puerto Varas", "Castro", "Ancud", "Chonchi", "Curaco de Vélez", "Dalcahue", "Puqueldón", "Queilén", "Quellón", "Quemchi", "Quinchao", "Osorno", "Puerto Octay", "Purranque", "Puyehue", "Río Negro", "San Pablo", "San Juan de la Costa", "Hualaihué", "Palena", "Chaitén", "Futaleufú"],
    "Aysén": ["Coyhaique", "Aysén", "Cisnes", "Guaitecas", "Lago Verde", "Río Ibáñez", "Chile Chico", "O'Higgins", "Tortel"],
    "Magallanes": ["Punta Arenas", "Laguna Blanca", "Río Verde", "San Gregorio", "Porvenir", "Primavera", "Timaukel", "Cabo de Hornos", "Antártica", "Torres del Paine"]
};